services:
  coffee-back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coffee-back
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    networks:
      - coffee-network
    volumes:
      - /home/ubuntu/app/.oci:/home/ubuntu/app/.oci:ro

networks:
  coffee-network:
    external: true